apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: techtrends
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
