apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
