apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends-sandbox
  ports:
  - protocol: TCP
    port: 4111
    targetPort: 3111
  type: ClusterIP