apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - name: 4111-3111
    port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP
status:
  loadBalancer: {}
