apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  ports:
    - port: 4111
      protocol: TCP
      targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP
