## The chart API version
apiVersion: v1
## The name of the chart. 
## In this case,  the chart name is`python-helloworld `.
name: nginx-alpine 
## A single-sentence description of this project
description: Install nginx alpine
## A list of keywords about this project to quickly identify the chart's capabilities.
keywords:
- nginx
- alpine 
## The chart version, here set to `3.7.0`
version: 1.0.0
## List of maintainers, their names, and method of contact
maintainers:
- name: guybourne 
  email: gbourne@abc.com